### ISSUE TITLE
VSMF4720-GS08 - obsolete

### ISSUE THREAD

**Issue by mewilliams** [tedlanghorst/OpenOBS#22]
I'm looking for parts to construct an OpenOBS. Digikey and Mouser both have show the NIR emiting diode listed in your parts list (VSMF4720-GS08) as obsolete and unavailable. Can you recommend a different sensor?  Thanks!

**Comment by tedlanghorst** [comment]
Sorry- just now saw this after your email! I've added alternative parts for both the NIR emitter and power MOSFET.
